{% set name = "pynsee" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynsee-{{ version }}.tar.gz
  sha256: fc7af5370ecbf7a8ea08f4a247e37a46d91bac5dd7191da627c602fd5661118e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[full] -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas >= 2.2.0, < 3.0
    - geopandas >= 1.0, < 2.0
    - pyarrow >= 17.0
    - tqdm >= 4.56
    - platformdirs >= 4
    - unidecode >= 1.3
    - urllib3 >= 2.2
    - shapely >= 2
    - requests >= 2.32
    - requests-ratelimiter >= 0.7

test:
  imports:
    - pynsee
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pynsee.readthedocs.io/en/latest/
  summary: Tools to Easily Search and Download French Data From INSEE and IGN APIs
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - hadrilec
