{% set name = "pynsee" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynsee-{{ version }}.tar.gz
  sha256: 856b8271b86d445444cb64dfbb517e492ed62d60782acb2e272eb5c6ad2708f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[full] -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas >=0.24.2
    - tqdm >=4.56.0
    - requests >=2.23
    - platformdirs 
    - unidecode >=1.1.0
    - shapely >=1.8.0
    - urllib3
    - pyarrow

test:
  imports:
    - pynsee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pynsee.readthedocs.io/en/latest/
  summary: Tools to Easily Search and Download French Data From INSEE and IGN APIs
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - hadrilec
