{% set name = "pynsee" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynsee-{{ version }}.tar.gz
  sha256: fa46d8790cc331d55f8083bb2f241ae38ad1acca1d5b98f3af88d22b27eca171

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[full] -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=0.24.2
    - tqdm >=4.56.0
    - requests >=2.23
    - appdirs >=1.4.4
    - unidecode >=1.1.0
    - shapely >=1.8.0,<2.0
    - urllib3

test:
  imports:
    - pynsee
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pynsee.readthedocs.io/en/latest/
  summary: Tools to Easily Search and Download French Data From INSEE and IGN APIs
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - hadrilec
