{% set name = "pynsee" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynsee-{{ version }}.tar.gz
  sha256: 7036ecb5de4337bc8009ca1ac77f50725933808b1fdb81f6786f2c71e900817c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install .[full] -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas >=0.24.2
    - tqdm >=4.56.0
    - requests >=2.23
    - appdirs >=1.4.4
    - unidecode >=1.1.0
    - shapely >=1.8.0,<2.0
    - urllib3

test:
  imports:
    - pynsee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pynsee.readthedocs.io/en/latest/
  summary: Tools to Easily Search and Download French Data From INSEE and IGN APIs
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - hadrilec
